# Generated by Django 6.0.2 on 2026-03-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='altitude',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=24),
            preserve_default=False,
        ),
    ]
