# Generated by Django 6.0.2 on 2026-03-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_city_altitude_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='altitude',
            new_name='elevation',
        ),
    ]
