# Generated by Django 6.0.2 on 2026-03-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_rename_altitude_city_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='italia'),
        ),
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.CharField(default='IT', max_length=10),
        ),
    ]
