# Generated by Django 6.0.2 on 2026-03-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0004_city_country_city_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
    ]
