# Generated by Django 6.0.2 on 2026-03-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0006_alter_city_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AlterField(
            model_name='city',
            name='elevation',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
