# Generated by Django 6.0.2 on 2026-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0007_remove_city_country_alter_city_elevation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'country_code'), name='unique_city_country'),
        ),
    ]
