# Generated by Django 6.0.2 on 2026-03-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0008_city_unique_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
