# Generated by Django 6.0.2 on 2026-03-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0009_city_country'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='city',
            name='unique_city_country',
        ),
    ]
